# Generated by Django 4.1.1 on 2022-09-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=125, verbose_name='название на русском')),
                ('title_en', models.CharField(max_length=125, verbose_name='название на английском')),
                ('title_jp', models.CharField(max_length=125, verbose_name='название на японском')),
                ('description', models.TextField(verbose_name='Описание аниме')),
                ('cover', models.ImageField(upload_to='media/covers/', verbose_name='Обложка аниме')),
                ('type', models.CharField(choices=[('Tv', 'Tv serial'), ('Web', 'Web serial'), ('Streaming', 'Streaming serial')], max_length=125, verbose_name='Тип аниме')),
                ('date_publish', models.DateField(verbose_name='Дата выхода аниме')),
                ('status', models.CharField(choices=[('Скоро выйдет', 'Скоро выйдет'), ('Продолжается', 'Продолжается'), ('Завершен', 'Завершен'), ('Приостановлен', 'Приостановлен'), ('В бане', 'В бане'), ('Редактура', 'Редактура')], max_length=125)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг аниме')),
                ('duration_per_episode', models.CharField(max_length=125, verbose_name='продолжительность на эпизод')),
                ('quality', models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('HD', 'HD'), ('4K', '4K'), ('8K', '8K')], max_length=125, verbose_name='Разрешение видео')),
                ('count_of_views', models.PositiveIntegerField(verbose_name='Количество просмотров')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('age_limit', models.PositiveSmallIntegerField(choices=[(3, 'pg-3'), (7, 'pg-7'), (12, 'pg-12'), (16, 'pg-16'), (18, 'pg-18')], verbose_name='Рейтинг PG')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Название студии')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Название сезона')),
                ('date_publish', models.DateField(verbose_name='Дата выпуска сезона')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.anime', verbose_name='Аниме')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Название эпизода')),
                ('file', models.FileField(upload_to='media/files/')),
                ('date_publish', models.DateField(verbose_name='Дата выпуска cерии')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('description', models.TextField(verbose_name='Описание эпизода')),
                ('cover', models.ImageField(upload_to='media/episode/covers/', verbose_name='обложка эпизода')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.season', verbose_name='Сезон')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(to='app.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(to='app.studio', verbose_name='Студии'),
        ),
    ]
