# Generated by Django 4.1.1 on 2022-09-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.AddField(
            model_name='season',
            name='total_episodes_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Общее количество серий которые планируются'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='total_episodes_released_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Общее количество серий которые вышли'),
            preserve_default=False,
        ),
    ]
