# Generated by Django 4.1.1 on 2022-09-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_anime_options_season_total_episodes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='app.season', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='season',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='app.anime', verbose_name='Аниме'),
        ),
    ]
