# Generated by Django 4.1.1 on 2022-09-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_anime_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='app.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(related_name='studios', to='app.studio', verbose_name='Студии'),
        ),
    ]
