# Generated by Django 4.1.1 on 2022-09-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_anime_genres_alter_anime_studios'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер сезона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер сезона'),
            preserve_default=False,
        ),
    ]
