# Generated by Django 4.1.1 on 2022-09-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_episode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер эпизода'),
            preserve_default=False,
        ),
    ]
