# Generated by Django 4.1.1 on 2022-09-23 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_episode_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewieEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Коментарий')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rewie_episode', to='app.episode')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_anime', to='app.anime', verbose_name='Для какого аниме?')),
            ],
        ),
    ]
