# Generated by Django 4.1.1 on 2022-09-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_animeepisodereview_animereview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='count_of_comments',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество комментариев'),
            preserve_default=False,
        ),
    ]
