# Generated by Django 4.1.1 on 2022-09-27 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_anime_count_of_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='count_of_votes',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество оценок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animereview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=5), django.core.validators.MinValueValidator(limit_value=1)]),
            preserve_default=False,
        ),
    ]
